version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
        auth:
          username: $DOCKER_HUB_PASSWORD
          password: $DOCKER_HUB_USER_NAME
    steps:
      - checkout
      - run: echo "hello world"

