version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: "${AWS_ACCESS_KEY_ID}"
          aws-secret-access-key: "${AWS_SECRET_ACCESS_KEY}"
          repo: ecr-tutorial
          tag: "${CIRCLE_SHA1}"
