AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Project Name
      Parameters:
        - PJPrefix
    - Label:
        default: AWS Account
      Parameters:
        - AWSAccountID
    - Label:
        default: Security Group
      Parameters:
        - SecurityGroup
    - Label:
        default: Subnet
      Parameters:
        - Subnet
    - Label:
        default: Docker Image
      Parameters:
        - DockerImage

Parameters:
  PJPrefix:
    ConstraintDescription: Project Name
    AllowedPattern: "[a-zA-Z-]*"
    Type: String
  AWSAccountID:
    ConstraintDescription: AWS Account ID
    MinLength: 12
    MaxLength: 12
    AllowedPattern: "[0-9]*"
    Type: String
  SecurityGroup:
    ConstraintDescription: Security Group
    Type: String
  Subnet:
    ConstraintDescription: Subnet
    Type: String
  DockerImage:
    ConstraintDescription: Docker Image
    Type: String

Resources:
  # ------------------------------------------------ #
  # Create Cluster                                   #
  # ------------------------------------------------ #
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Sub "${PJPrefix}-cluster"
  # ------------------------------------------------ #
  # Create Task Definition                           #
  # ------------------------------------------------ #
  Taskdefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image: !Sub "${DockerImage}"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: awslogs-ecs
              awslogs-region: ap-northeast-1
              awslogs-create-group: true
              awslogs-stream-prefix: !Sub "awslogs-${PJPrefix}-app"
          Name: !Sub "${PJPrefix}-app"
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
      Cpu: '256'
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWSAccountID}:role/ecsTaskExecutionRole"
      Family: !Sub "${PJPrefix}-task-definition"
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        OperatingSystemFamily: LINUX               
  # ------------------------------------------------ #
  # Create Service                                   #
  # ------------------------------------------------ #
  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      ServiceName: !Sub "${PJPrefix}-service"
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Sub "${SecurityGroup}"
          Subnets:
            - !Sub "${Subnet}"
      TaskDefinition: !Ref Taskdefinition
